# Generated by Django 5.0.3 on 2025-12-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('user', models.TextField(primary_key=True, serialize=False)),
                ('blocked', models.TextField()),
            ],
        ),
    ]
